### ISSUE TITLE
Create pattern to designate when request is waiting on the server

### ISSUE THREAD

**Issue by suprenant** [18F/cg-design#14]
@suprenant commented on [Mon Sep 26 2016](https://github.com/18F/cg-dashboard/issues/621)

What we're after: 
- General design pattern for when actions are taken (like bind app, or add route) and we're waiting for the request to the server to finish. 
- Should there be a spinner? No spinner? 
- We have loading pattern for fetched/initial load
- Related to designs here: https://github.com/18F/cg-design/issues/5
- Don’t have a pattern for binding a route, which takes awhile
- Do we want to show UI here?
- We haven’t really needed this personally (we have fast computers), but other users may need it

This is not blocking anything, but important

**Comment by thisisdano** [comment]
This came up here, too: https://github.com/18F/cg-dashboard/issues/601

![service states 2x](https://cloud.githubusercontent.com/assets/11464021/18878027/02768a02-8484-11e6-9634-484dbe3e7954.png)

**Comment by thisisdano** [comment]
@msecret @vz3 ^^^

**Comment by msecret** [comment]
What if we don't know what the request is? Like if we don't know if it's "Starting", "Deleting", etc? We'll just show the loader? Trying to think of all possible scenarios now.

**Comment by suprenant** [comment]
Looking for @vz3 feedback here

**Comment by suprenant** [comment]
This has been approved!
