### ISSUE TITLE
Write LICENSE and CONTRIBUTING files for cg-design repository

### ISSUE THREAD

**Issue by brittag** [18F/cg-design#15]
In order for us to clearly communicate the license status of our work and of other people's work that we're using (and to comply with their licenses), we should have LICENSE and CONTRIBUTING files in this repository.

We can use [18F's standard LICENSE and CONTRIBUTING files](https://github.com/18F/open-source-policy/blob/master/practice.md#how-to-license-18f-repos) as a basis, and we should include specific documentation of the licenses/sources for the non-18F files in this repository. We could model this after https://github.com/18F/web-design-standards/blob/staging/LICENSE.md

**Comment by thisisdano** [comment]
The `18Franklin` font files linked are a fork of https://github.com/impallari/Libre-Franklin and would pick up the same license (SIL Open Font License v1.1 )
