### ISSUE TITLE
Create and apply new theme name for Liberator

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-design#17]
We should have a theme name that better reflects our priorities, goals, and design principles for the sprint. I have an idea.

Previous working doc: 
https://docs.google.com/document/d/1IRVdiRyzZJrxxX1ETi4aYmHpQnDmzQNGZ6t76L3Re9Q/edit

Acceptance criteria: 
- [x] Schedule time to meet and discuss with the team
- [x] Determine outcome
- [x]  Share with program-level team

Replace Liberator with new name where appropriate:
- [x] Calendar events
- [x] Slack channels (Marco/Andrew)
- [x] Repo tag(s) 
- [x] Team roster
- [x] Documentation (onboarding docs, also find and replace) (Aaron)
- [x] Sprint review deck
- [x] Tock
- [x] Float
- [x] Aha
- [x] PI8 cloud.gov planning briefing: https://docs.google.com/presentation/d/1HKnvcNBkPkhTcjkARxxc7M3Ix8LpDBCfG3lefDEafY8/edit#slide=id.g111bc0346b_0_2246 (needs tagline and imagery)

Nice to do:
- [x] Find some imagery: 
  Flight of the Navigator?
  No compasses! No spyglasses!
  No steampunk
  No HAL

**Comment by suprenant** [comment]
Picking this up. Scheduled meeting for next week!

**Comment by suprenant** [comment]
We met on this today and made some good progress. Reconvening tomorrow to wrap this up

**Comment by suprenant** [comment]
Made some progress here. Dropped our action items of where to change the name into this issue. @adborden as soon as you and I wrap up our items, we can consider this done.

**Comment by suprenant** [comment]
OK, this is done after we update the documentation. I took a pass at imagery and tagline, but we can update this further if we want.

**Comment by suprenant** [comment]
Ah, also noticed that we need to change this in Float and Tock. I changed Float, pinging #tock.
