### ISSUE TITLE
Develop design principles

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-design#18]
Why do we make the design decisions we make? Design principles help build alignment and clarify priorities and reasoning by tying decision-making guidelines to strategic goals. I'd like to make a couple of these.

This will probably include a little questionnaire for the cg team to complete async.

Related items we discussed before: 
https://docs.google.com/document/d/1SHziUTLs14y769Jt01jKC-OmTlfrRdeIbi5LE3kjRPg/edit

Artifact: 
https://github.com/18F/cg-product/wiki/Design-principles

Acceptance criteria: 
- [x] Draft preliminary principles
- [x] Schedule time to meet and discuss with the team

**Comment by suprenant** [comment]
Will set up meeting to discuss this along with https://github.com/18F/cg-product/issues/352

**Comment by suprenant** [comment]
Scheduled meeting for next Thursday. Closing this up.
