### ISSUE TITLE
Address accessibility and usability issues

### ISSUE THREAD

**Issue by vz3** [18F/cg-design#20]
Please provide feedback from recent cg-style/docs changes here.

**Comment by brittag** [comment]
- If I look at the homepage on a typical 13" laptop instead of the big workstation screen, it feels like it needs a lot of scrolling to get information about cloud.gov.
- Not sure about the blue increased-size text on pages like https://cloud.gov/docs/getting-started/your-first-deploy/ - blue usually reads as "link" to me.
- Update post pages have a style problem that makes the nav unclickable (such as https://cloud.gov/updates/2016-06-15-auth-ssh-changes/).

**Comment by thisisdano** [comment]
Moving to something like this for the doc deks:

![screen shot 2016-11-01 at 2 49 07 pm](https://cloud.githubusercontent.com/assets/11464021/19908909/800d58e0-a042-11e6-9b0e-1b3ddbde803d.png)

**Comment by brittag** [comment]
Cool! More notes:
- In the docs right now, the first paragraph isn't always meaningful to highlight - for example, https://cloud.gov/overview/pricing/rates/ is a bit odd.
- At the bottom of docs pages, the "Built with ❤️  by the cloud.gov team." has a little extra space after the ❤️ .
- Noticing again that the content at https://cloud.gov/updates/ is still sort of oddly wide - filed a long time ago at https://github.com/18F/cg-landing/issues/43
- cloud-gov-inquiries@gsa.gov at the bottom of https://cloud.gov/#contact is split into a couple lines now.

**Comment by mogul** [comment]
- The little “chainlink” permalink icon at the end of in-content headers in https://cloud.gov/docs is invisible with the new styling until you actually click on it. [Example](https://cloud.gov/docs/ops/contingency-plan/#how-this-document-works)

**Comment by thisisdano** [comment]
todo
- [x] blue dek > gray
- [x] spacing in heart glyph
- [x] fix updates page styles
- [x] breaking email address in footer
- [x] update 18Franklin
- [x] show chainlink permalink
- [x] spacing bw h[0-6] and and [uo]l 
- [x] font size/use in tables
- [x] accessibility: dek color (actually OK; [link](http://webaim.org/resources/contrastchecker/?fcolor=8e8e8e&bcolor=ffffff) — this is large text)
- [x] accessibility: red on cream

NOT IN THIS PR:
- [ ] discuss use of dek in docs 
- [ ] vertical spacing on home, maybe icons
- [ ] accessibility: buttons in dash

**Comment by suprenant** [comment]
Add more space between the subhead ("A few things you can do here") and bulleted lists here:

![screen shot 2016-11-03 at 12 15 05 pm](https://cloud.githubusercontent.com/assets/1452369/19977527/e2ab8280-a1c1-11e6-8b31-097b2447edce.png)

**Comment by msecret** [comment]
### Accessibility issues

Color contrast issues on cg-dashboard
![image](https://cloud.githubusercontent.com/assets/1701077/19982647/1abdb9c0-a1c4-11e6-8667-b93b35bf3fb7.png)

![image](https://cloud.githubusercontent.com/assets/1701077/19982674/3723ee18-a1c4-11e6-964b-ddd6c51f1604.png)

Color contrast issues on cg-site
![screen shot 2016-11-01 at 12 46 54 pm](https://cloud.githubusercontent.com/assets/1701077/19982574/d5fdb13c-a1c3-11e6-8f94-80595e9af3b2.png)

![screen shot 2016-11-01 at 12 46 33 pm](https://cloud.githubusercontent.com/assets/1701077/19982573/d5f98f30-a1c3-11e6-9d31-4f85efd8d59d.png)

**Comment by thisisdano** [comment]
New design for Updates page and Individual updates: 

---

![screen shot 2016-11-08 at 9 04 08 am](https://cloud.githubusercontent.com/assets/11464021/20108854/73eea35c-a592-11e6-89dd-60799fe6439e.png)

---

![screen shot 2016-11-08 at 9 04 24 am](https://cloud.githubusercontent.com/assets/11464021/20108860/7904b566-a592-11e6-9cbb-d885b2429011.png)

---

The single view would be mostly for linking — I'm including full text on the Updates overview since the summary was never that great and the content was easy enough to skim past.

@brittag @berndverst

**Comment by thisisdano** [comment]
I'm skipping the accessibility issue for gray buttons as I don't think that gray button style will continue much longer like that. Gray buttons shd only be for inactive items.

**Comment by thisisdano** [comment]
Addressed with the following PRs:

https://github.com/18F/cg-style/pull/179
https://github.com/18F/cg-site/pull/535

@msecret

**Comment by brittag** [comment]
Thanks @thisisdano! I like the overall style; it fits with the documentation style. I'm hesitant on making the first paragraph larger on the single-post view, basically for "don't make me think" reasons - it's just a typical post format where each paragraph has content, rather than the first paragraph being special, so I don't think it "fits" the content to highlight the first paragraph in a special way.

Also ccing @jameshupp in case he has content design thoughts. :D

**Comment by thisisdano** [comment]
I see the point about first grafs not necessarily being special — and I _do_ see the case in the updates to revert to a standard p. 

Counterproposal: maybe the first graf _should_ be a bit special? Or function well if it _is_ special? There aren't that many updates, and only a couple instances where the dek is more odd than it should be.

**Comment by brittag** [comment]
Hm, one bit of context I have in mind is that our updates need to be simple and short posts - we have to put anything at the level of complexity of a full blog post on the 18F blog. We could specifically write deks/subheds for our posts, newspaper-style, but I'm inclined to instead keep our updates really plain and simple. :)

I'd defer to Skyporter squad folks on styling for this though!

**Comment by thisisdano** [comment]
I don't think simple content and good content design are mutually exclusive. Sounds like it's worth thinking about what an "Update" is, since the updates page has a broad grab-bag of content now.

**Comment by jameshupp** [comment]
So at least recently, most of our posts have had a first paragraph that fits neatly into this different style. And I think it is a useful content tool: your first paragraph should summarize everything to follow in as simple a way as possible. It's the other side of don't make me think: don't make me read. We're not spinning yarns here; if we can give someone the tl;dr in the first paragraph, we should.

The one question I'd have is how a post looks when it is only one paragraph. Could we see how `Full steam ahead on FedRAMP assessment` would look? Would the styling be tied to there being more than one paragraph? More than two? If anything, I think it looks oddest at two paragraphs, unless the first paragraph is only one sentence.

I like how this paragraph looks in general, but 2-4 paragraphs seems like a good bet for length going forward. Does that affect the choice?

**Comment by thisisdano** [comment]
Pretty much agreed on all points. 

I'd imagine that a good template for an update is:

[title]
[Short descriptive graf about the update]
[Longer contextualization of the update]
[Bullet point summary of update]
[Short closing graf]

**Comment by berndverst** [comment]
I want to stress that release notes are a bit different from one-off update posts. However we intend to post release notes at `/updates`.

I would like to caution against using a blog-like style / layout for what are technical release notes aimed at developers.

You will find that release notes usually look simple and plain when comparing with other developer focussed products (e.g. Heroku, Google App Engine, AWS, etc)

**Comment by thisisdano** [comment]
I'd only say let's just get to posting them and then we can adapt to the proper presentation. Dunno if we want to have a separate style for release notes vs. other updates (if there are any) — but we can leave that option open.
