### ISSUE TITLE
Refine header/breadcrumb layout and interaction

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-design#24]
The header and breadcrumb nav work together to communicate the user's location and allow navigation to other views. A successful header/breadcrumb:

- [ ] Clearly communicates the specific view
- [ ] Clearly communicates the relationship of the view to the hierarchy
- [ ] Allows navigation within the hierarchy
- [ ] Clarifies the model
- [ ] Uses space well
- [ ] Feels lightweight and efficient

When complete:
- [ ] Design fulfills success requirements
- [ ] Design prototype has been tested
- [ ] Design is refined based on testing
- [ ] Dev gets new design/functional requirements
- [ ] New sketch files posted
- [ ] Invision prototype posted

**Comment by thisisdano** [comment]
More to come, but here's the Invision: https://gsa.invisionapp.com/share/838UY596S#/208123072_Overview--closed

**Comment by thisisdano** [comment]
@vz3 @line47 check it

**Comment by thisisdano** [comment]
This relates to https://github.com/18F/cg-dashboard/issues/648

**Comment by vz3** [comment]
I think this looks great. I'll have some feedback on some of the visual design details, but I think the interactions/navigation is in a good place (i.e. ready for testing 18f/cg-dashboard#716).
