### ISSUE TITLE
Clicking search button doesn't give focus to search box

### ISSUE THREAD

**Issue by brittag** [18F/cg-design#25]
In order for cloud.gov site visitors to quickly search our site, clicking the search button should immediately give focus to the search box. From observation and personal experience, I believe this is what users expect when they click a search button that reveals a search box.

![screen shot 2016-11-28 at 12 37 07 pm](https://cloud.githubusercontent.com/assets/391313/20685036/7fc02658-b567-11e6-99aa-61a0493083eb.png)

**Acceptance criteria**

- [x] Clicking the search button gives focus to the search box

cc @thisisdano

**Comment by thisisdano** [comment]
👍 
Glad to finally see this.
And If we _really_ wanted to do it proper, we could also dismiss it with `esc` and trigger it with `/` 😀

**Comment by msecret** [comment]
This would be a good thing for @line47 to look at.

**Comment by brittag** [comment]
Hmm reopening since there may be a bit of lingering work here: when I click the search button on the homepage or updates pages, focus goes to the search box, but that doesn't seem to happen on "overview" or "documentation" pages.

**Comment by line47** [comment]
The overview and documentation sections have their own footer files which are not including index.js which has the JS for the search focusing. I can update the Overview and Documentation footers to include this JS.

**Comment by line47** [comment]
Also, is there a reason the footer changes from the homepage to the docs to the updates page? Can cg-site use the same footer? @brittag

**Comment by brittag** [comment]
Interesting - it sounds good to me for all of these to have the same footer! I don't know of any reason to make it different.

**Comment by line47** [comment]
Great! We can certainly do that. Should we use the footer seen here? https://cloud.gov/ or the footer as seen here? https://cloud.gov/docs/help/

**Comment by brittag** [comment]
Let's use the https://cloud.gov/ footer! It looks nicer, and it's more informative.

**Comment by brittag** [comment]
I found one page that now has a weird footer: https://cloud.gov/docs/services/ - I suspect this is because https://github.com/18F/cg-site/blob/master/layouts/docs/services.html doesn't match the other pages.

**Comment by brittag** [comment]
The pages under "overview" also have this weird footer, such as https://cloud.gov/overview/overview/what-is-cloudgov/

**Comment by line47** [comment]
Thanks for catching this @brittag, I'll have a look and get those pages updated as well.

**Comment by line47** [comment]
Looks like this was already fixed in https://github.com/18F/cg-site/pull/673 Awesome!

**Comment by brittag** [comment]
Yay! This looks complete to me, so I'll accept/close this. Thanks!
