### ISSUE TITLE
Add route URL to confirmation message when unbinding or deleting

### ISSUE THREAD

**Issue by line47** [18F/cg-design#27]
What we're after:

### Route Unbinding
When clicking unbind on a bound route the route URL is replaced with "Unbind this route from this app?" thus hiding the route URL.

Replace the text "this route" with the URL of the route. 
For example, "Unbind `great.apps.cloud.gov` route from this app?"

### Mockup
<img width="928" alt="unbinding" src="https://cloud.githubusercontent.com/assets/1449852/20685870/3a64e0ae-b584-11e6-942b-2379dfdefa27.png">

### Route Deleting
When clicking delete on an available route the route URL is replaced with "Delete this route from this space?" thus hiding the route URL.

Replace the text "this route" with the URL of the route.
For example, "Delete `great.apps.cloud.gov` route from this space?"

### Mockup
<img width="917" alt="deleting" src="https://cloud.githubusercontent.com/assets/1449852/20689130/c8a9e8a2-b591-11e6-9bdc-d49cf2df8ef5.png">

### Acceptance criteria:
- [x] When clicking unbind on a bound route, a valid URL is displayed and is clickable, as in "Unbind `great.apps.cloud.gov` route from this app?"
- [x] When deleting a bound route, a valid URL is displayed and is clickable, as in "Delete `great.apps.cloud.gov` route from this space?"

**Comment by line47** [comment]
I'm trying to get the clickable URL in the message but `{displayURL} isn't working.

### code
```  get confirmationMsg() {
    const { domain_name, host, path } = this.props.route;
    const url = formatRoute(domain_name, host, path);
    const displayUrl = <a href={ url } title="See app route">{ url }</a>;
    return (RouteStore.isRouteBoundToApp(this.props.route)) ?
      `Unbind ${displayUrl} route from this app?` :
      `Delete ${url} route from this space?`;
  }
```
### output
<img width="424" alt="screen shot 2016-12-07 at 10 13 15 am" src="https://cloud.githubusercontent.com/assets/1449852/20973275/08a9bb8c-bc66-11e6-845b-594457b0e633.png">

@msecret or @adborden can you take a look?

**Comment by msecret** [comment]
So this ``Unbind ${displayUrl} route from this app?`` is using ES6 string interpolation, not React, so it only seems `displayUrl` has an object rather then a React component. Maybe trye

```js
return (RouteStore.isRouteBoundToApp(this.props.route)) ?
      <span>Unbind ${displayUrl} route from this app?</span> :
      <span>Delete ${url} route from this space?</span>;
```

**Comment by line47** [comment]
Thanks @msecret, that worked out great!

**Comment by adborden** [comment]
LGTM
