### ISSUE TITLE
Create base pattern library

### ISSUE THREAD

**Issue by vz3** [18F/cg-design#3]
`# = Template`
`## = Organism`
`### = Molecule`
`- = Atom`

Additionally I've marked templates with (tier-)`(1)` and organisms with `(2)` and bulleted items are atoms.
# Universal (1)
- Button
- Helper text
- Pin (non-mvp)
## Typography (2)
- Display
- Feature text
- H1-H6
- Monotype
- Helper txt
## Site-wide header (2)
- Logo
### Navigation (3)
- Menu
- Username display
- Log out 
## Site-wide footer (2)
- ???
# Landing (1)
## Notifications (2)
- Priority indicator
- Date+Time
- Text
### Org/space/app card (3)
- Org/space/app name
- Org/space/app label
- Org/space/app notification indicator
- Org/space/app status
- Expandable?
## User management (2)
- ???
# Organization landing (1)
### Space card (3)
- Space name
- Space notification indicator
# Space landing (1)
### App card (3)
- App name
- App notification indicator
# App (1)
## Activity log (2)
- Low-priority activity (Most activity)
- Medium-priority activity (User edits, pushes, rollbacks(?)
- High-priority activity (Errors)
## App settings (3)
- ??? (dependent upon manifest capabilities)

**Comment by juliasolorzano** [comment]
Should this be in the `In Progress` column?

**Comment by thisisdano** [comment]
OK — I'm working through getting my Sketch file in order. Right now there's only one, but maybe we'll split it into multiple files in the future.

@juliaelman I added you to the InVision project. @vz3 you should already be on it. If you sync, you should get the files in `invision/GSA/cg-atomic-bass/assets/source files`

The design work is up for commenting here:
https://gsa.invisionapp.com/share/C88GJDUWR

I'll be adding and refining these pages/files on an ongoing basis.

**Comment by suprenant** [comment]
Following up on the note @juliaelman made last week. I believe this (or a story related to it) should be in the In Progress column. Moving it there now. 

Let's check in on how we're moving stories during our mid-sprint review tomorrow (unless folks want to give any thoughts here)

**Comment by suprenant** [comment]
Continuing to tidy our redundant issues. Elements from https://github.com/18F/cg-dashboard/issues/532

We will be following Atomic Design for this:
http://bradfrost.com/blog/post/atomic-web-design/

The pattern library should be delivered via PDF+Sketch for implementation by front end devs.

Separate things to do:
- Create issues for separate parts in cg-design

**Comment by suprenant** [comment]
@adborden adding you here as I think we'll want you to work with Marco on the pattern work on the dev side.  I don't think this issue is shovel-ready yet, but FYI

cc @msecret

**Comment by suprenant** [comment]
Redundant with: https://github.com/18F/cg-design/issues/11. Closing this up
