### ISSUE TITLE
Design services 

### ISSUE THREAD

**Issue by vz3** [18F/cg-design#6]

**Comment by vz3** [comment]
Sketch: [uswds cg fork.zip](https://github.com/18F/cg-design/files/431242/uswds.cg.fork.zip)

![services](https://cloud.githubusercontent.com/assets/582918/17873758/7779e408-6895-11e6-9062-533dd691bfe3.png)

**Comment by vz3** [comment]
Outstanding issues:
- Visual heirarchy is still super flat.
- Validate 508 on the warning red background.
- Consider adding more relevant info to each service. Perhaps usage?
- The actual stopped warning can be polished (Warning with hyperlink next to it feels strange)
- Do we need the unbind/bind glyph?

**Comment by vz3** [comment]
![services 2](https://cloud.githubusercontent.com/assets/582918/17944504/04f25ed6-6a0e-11e6-8fdb-f9054642455a.png)

**Comment by msecret** [comment]
@vz3 looking at the data in the API, the state for an instance isn't exactly started/stopped. Heres an idea:

_last_operation.type_: create, update, delete
_last_operation.state_: in progress, succeeded, failed

So you might say if the last create operation is in a failed state, then it's stopped. Or if the create or update operation succeeded, it's in a running state.

So should we take the data it's giving us and interpret it to whether it's _Running_, _Stopped_, _Processing_ (updating). Or should we provide more specific information based on the data, like _Creation successful_, _Updating failed_?

Also, still trying to figure out if we can get logs specific for the instance, not looking easy right now.

@jeremiak does this make sense.

**Comment by jeremiak** [comment]
It does make sense, but I think "stopped" isn't going to be an accurate reflection of the state of the service. Take a database service. If I think of a DB as "stopped", I think that it still retains the data, I just can't access it. But in this case, the service instance would be deleted and therefore the data would be destroyed and unrecoverable.

**Comment by vz3** [comment]
@msecret Let me know if there's anything design owes you on this?

**Comment by suprenant** [comment]
Per @vz3, highlighting that there is a dependency here on 18f/cg-design#8

**Comment by thisisdano** [comment]
Here's a pass based on the Routes styles from https://github.com/18F/cg-dashboard/issues/582
Invision: https://gsa.invisionapp.com/share/9T8GMJ8B8#/190897181_App-Services-6c--default

<img width="961" alt="services sketch" src="https://cloud.githubusercontent.com/assets/11464021/18758493/2cf44556-80ad-11e6-9b8f-b1358d96d0b5.png">

There's a radio input to display cost or service version

**Comment by suprenant** [comment]
^ @mogul per stand-up

**Comment by mogul** [comment]
Looks nice... Do I leave comments here or in Invision? (Feels a bit weird to have the radio button swap out the entire icon and name, rather than just the version, to show the cost.)

**Comment by thisisdano** [comment]
@mogul we don't have a determined comment flow BUT here is probably best as a canonical reference

The invision will always be changing.

Lemme see what I can do to make `version`/`cost` switching better. If we DID do a full swap (as pictured above) perhaps `kind` is a better category?

**Comment by mogul** [comment]
Definitely. 👍  

Some things to keep in mind: 
- We want to make it easy for people to learn all the nitty-gritty details about a service: Docs on how to use it, plan differences, whether it's experimental or supported, etc. We can add those details to docs.cloud.gov, but people should be able to find their way there easily from a given service instance in the UI.
- Services  can have their own management interfaces. We're not leveraging this now and probably should in future. 

So you might want to think about how we signal when additional web-based documentation and/or controls are available for a service.

**Comment by thisisdano** [comment]
Yes, thanks. I've got those augmentations in mind — while I haven't sketched anything yet, I'm definitely thinking about it.

Do we have any our own example of the kind of service details content we'd be providing? (If not, I'll just continue to use Heroku as the model)

**Comment by vz3** [comment]
I can go into more detail but quick thoughts on this are that we should be able to show version and cost at the same time. I'd also like to see the visual hierarchy changed to emphasize stopped states and significantly deemphasize running states.

Existing hierarchy
- Running or stopped state
- Icon
- App Name
- Unbind
- Version
- Service instance name

Proposed hierarchy
- Stopped state if stopped (Functioning assumption needs validation: stopped service=bad)
- Icon
- App name
- Cost
- Service instance name
- Running state if running
- Unbind

**Comment by thisisdano** [comment]
Updated.

<img width="488" alt="screen shot 2016-09-22 at 11 47 11 am" src="https://cloud.githubusercontent.com/assets/11464021/18761573/56d15a46-80ba-11e6-84a1-1bc0814369d3.png">

**Comment by msecret** [comment]
So a problem with the design ^  we simply don't have all that information right now. Here's the info we have for a typical Postgres instance:
- name: name given to the instance by user upon creation
- description: our own description, pretty bland, "Shared infrastructure for Postgres DB"
- service name: "rds"
- service description: "RDS Database Broker"
- service plan name: our own name, also not descriptive, "shared-psql"
- service plan "display name": seems to be based on what plan it is rather then the service,"Free Shared Plan"
- bullets?: seems to be arbituary data, this one has both "Shared RDS Instance", and "Postgres instance".
- cost: in amount monthly
- free: true for everything now, separate from cost for some reason (as in cost = 0  doesn't necessarily me it's free)

In order to make that UI above, we're going to have to add more information on the backend, I don't know how possible/easy that is.

**Comment by mogul** [comment]
It's very easy to edit those fields (service names, plan names, descriptions) to make them more informative, and it's long past due! Basically they're just parameters on the broker.

**Comment by msecret** [comment]
@thisisdano it sounds like we should just edit the fields to what we want. We can edit multiple fields. Something to keep on mind: we're not pulling in the "service" data on the app page, so we should try and keep the data in the instance and the service plan.

**Comment by thisisdano** [comment]
@msecret Can you clarify what you mean by this: 

> we're not pulling in the "service" data on the app page, so we should try and keep the data in the instance and the service plan.

Does this mean that we should make sure to show the complete data somewhere? Like, for instance, in the marketplace?

**Comment by msecret** [comment]
It just means when we manually edit the fields to include the more accurate data we want, I'd prefer if put it in fields besides the "service name" and "service description" because those are harder to access.

**Comment by mogul** [comment]
Note that there is additional metadata that can be returned along with the services listed via the /catalog API: 
https://docs.cloudfoundry.org/services/api.html#catalog-mgmt
https://docs.cloudfoundry.org/services/catalog-metadata.html

**Comment by msecret** [comment]
Waiting on https://github.com/18F/cg-style/pull/155, https://github.com/18F/cg-style/pull/154

**Comment by suprenant** [comment]
Moving this to Awaiting Acceptance as we discussed the design being done with @vz3 approving during sprint planning today. We can track the actual work and additional research in our other issues related to this work.
